package co.edu.usbcali.vas.model;
// Generated Jun 10, 2018 8:14:55 PM by Hibernate Tools 5.1.0.Final


import java.util.Date;

/**
 * SystemCompanyParameter generated by hbm2java
 */
public class SystemCompanyParameter  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String companyNit;
     private String companyName;
     private String companyAddress;
     private String companyEmail;
     private String companyWeb;
     private String companyPhone;
     private String companyLogoUrl;
     private String systemName;
     private String systemUrl;
     private String systemLogoUrl;
     private String systemVersion;
     private Date createdAt;
     private Date updatedAt;
     private String createdBy;
     private String updatedBy;

    public SystemCompanyParameter() {
    }

	
    public SystemCompanyParameter(Integer id, String code, Date createdAt, String createdBy) {
        this.id = id;
        this.code = code;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
    }
    public SystemCompanyParameter(Integer id, String code, String companyNit, String companyName, String companyAddress, String companyEmail, String companyWeb, String companyPhone, String companyLogoUrl, String systemName, String systemUrl, String systemLogoUrl, String systemVersion, Date createdAt, Date updatedAt, String createdBy, String updatedBy) {
       this.id = id;
       this.code = code;
       this.companyNit = companyNit;
       this.companyName = companyName;
       this.companyAddress = companyAddress;
       this.companyEmail = companyEmail;
       this.companyWeb = companyWeb;
       this.companyPhone = companyPhone;
       this.companyLogoUrl = companyLogoUrl;
       this.systemName = systemName;
       this.systemUrl = systemUrl;
       this.systemLogoUrl = systemLogoUrl;
       this.systemVersion = systemVersion;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getCompanyNit() {
        return this.companyNit;
    }
    
    public void setCompanyNit(String companyNit) {
        this.companyNit = companyNit;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getCompanyAddress() {
        return this.companyAddress;
    }
    
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress;
    }
    public String getCompanyEmail() {
        return this.companyEmail;
    }
    
    public void setCompanyEmail(String companyEmail) {
        this.companyEmail = companyEmail;
    }
    public String getCompanyWeb() {
        return this.companyWeb;
    }
    
    public void setCompanyWeb(String companyWeb) {
        this.companyWeb = companyWeb;
    }
    public String getCompanyPhone() {
        return this.companyPhone;
    }
    
    public void setCompanyPhone(String companyPhone) {
        this.companyPhone = companyPhone;
    }
    public String getCompanyLogoUrl() {
        return this.companyLogoUrl;
    }
    
    public void setCompanyLogoUrl(String companyLogoUrl) {
        this.companyLogoUrl = companyLogoUrl;
    }
    public String getSystemName() {
        return this.systemName;
    }
    
    public void setSystemName(String systemName) {
        this.systemName = systemName;
    }
    public String getSystemUrl() {
        return this.systemUrl;
    }
    
    public void setSystemUrl(String systemUrl) {
        this.systemUrl = systemUrl;
    }
    public String getSystemLogoUrl() {
        return this.systemLogoUrl;
    }
    
    public void setSystemLogoUrl(String systemLogoUrl) {
        this.systemLogoUrl = systemLogoUrl;
    }
    public String getSystemVersion() {
        return this.systemVersion;
    }
    
    public void setSystemVersion(String systemVersion) {
        this.systemVersion = systemVersion;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }




}


