package co.edu.usbcali.vas.model;
// Generated Mar 27, 2019 8:31:43 PM by Hibernate Tools 5.1.0.Final


import java.util.Date;

/**
 * VideoTransaction generated by hbm2java
 */
public class VideoTransaction  implements java.io.Serializable {


     private Long id;
     private Users users;
     private VideoStatus videoStatus;
     private VideoType videoType;
     private String mimeType;
     private String description;
     private String url;
     private String src;
     private String info;
     private String format;
     private String lenght;
     private String videoData;
     private String analyticData;
     private Long transferTime;
     private Long analysisTime;
     private Date createdAt;
     private Date updatedAt;
     private String createdBy;
     private String updatedBy;
     private String videoTransactionId;
     //
     private String urlPicture;

    public VideoTransaction() {
    }

	
    public VideoTransaction(Long id, Users users, VideoStatus videoStatus, VideoType videoType, String description, Date createdAt, String createdBy) {
        this.id = id;
        this.users = users;
        this.videoStatus = videoStatus;
        this.videoType = videoType;
        this.description = description;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
    }
    public VideoTransaction(Long id, Users users, VideoStatus videoStatus, VideoType videoType, String mimeType, String description, String url, String src, String info, String format, String lenght, String videoData, String analyticData, Long transferTime, Long analysisTime, Date createdAt, Date updatedAt, String createdBy, String updatedBy) {
       this.id = id;
       this.users = users;
       this.videoStatus = videoStatus;
       this.videoType = videoType;
       this.mimeType = mimeType;
       this.description = description;
       this.url = url;
       this.src = src;
       this.info = info;
       this.format = format;
       this.lenght = lenght;
       this.videoData = videoData;
       this.analyticData = analyticData;
       this.transferTime = transferTime;
       this.analysisTime = analysisTime;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public VideoStatus getVideoStatus() {
        return this.videoStatus;
    }
    
    public void setVideoStatus(VideoStatus videoStatus) {
        this.videoStatus = videoStatus;
    }
    public VideoType getVideoType() {
        return this.videoType;
    }
    
    public void setVideoType(VideoType videoType) {
        this.videoType = videoType;
    }
    public String getMimeType() {
        return this.mimeType;
    }
    
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getSrc() {
        return this.src;
    }
    
    public void setSrc(String src) {
        this.src = src;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }
    public String getLenght() {
        return this.lenght;
    }
    
    public void setLenght(String lenght) {
        this.lenght = lenght;
    }
    public String getVideoData() {
        return this.videoData;
    }
    
    public void setVideoData(String videoData) {
        this.videoData = videoData;
    }
    public String getAnalyticData() {
        return this.analyticData;
    }
    
    public void setAnalyticData(String analyticData) {
        this.analyticData = analyticData;
    }
    public Long getTransferTime() {
        return this.transferTime;
    }
    
    public void setTransferTime(Long transferTime) {
        this.transferTime = transferTime;
    }
    public Long getAnalysisTime() {
        return this.analysisTime;
    }
    
    public void setAnalysisTime(Long analysisTime) {
        this.analysisTime = analysisTime;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }


	public String getVideoTransactionId() {
		return videoTransactionId;
	}


	public void setVideoTransactionId(String videoTransactionId) {
		this.videoTransactionId = videoTransactionId;
	}


	public String getUrlPicture() {
		return urlPicture;
	}


	public void setUrlPicture(String urlPicture) {
		this.urlPicture = urlPicture;
	}




}


