package co.edu.usbcali.vas.model;
// Generated Jun 10, 2018 8:14:55 PM by Hibernate Tools 5.1.0.Final


import java.util.Date;

/**
 * Device generated by hbm2java
 */
public class Device  implements java.io.Serializable {


     private Integer id;
     private String description;
     private String ipAddress;
     private Integer port;
     private String login;
     private String password;
     private String serialNumber;
     private String channelAmount;
     private String model;
     private String manufacturer;
     private String type;
     private String location;
     private String note;
     private String active;
     private Date createdAt;
     private Date updatedAt;
     private String createdBy;
     private String updatedBy;

    public Device() {
    }

	
    public Device(Integer id, String description, String ipAddress, Integer port, String login, String password, String active, Date createdAt, String createdBy) {
        this.id = id;
        this.description = description;
        this.ipAddress = ipAddress;
        this.port = port;
        this.login = login;
        this.password = password;
        this.active = active;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
    }
    public Device(Integer id, String description, String ipAddress, Integer port, String login, String password, String serialNumber, String channelAmount, String model, String manufacturer, String type, String location, String note, String active, Date createdAt, Date updatedAt, String createdBy, String updatedBy) {
       this.id = id;
       this.description = description;
       this.ipAddress = ipAddress;
       this.port = port;
       this.login = login;
       this.password = password;
       this.serialNumber = serialNumber;
       this.channelAmount = channelAmount;
       this.model = model;
       this.manufacturer = manufacturer;
       this.type = type;
       this.location = location;
       this.note = note;
       this.active = active;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    public Integer getPort() {
        return this.port;
    }
    
    public void setPort(Integer port) {
        this.port = port;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSerialNumber() {
        return this.serialNumber;
    }
    
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }
    public String getChannelAmount() {
        return this.channelAmount;
    }
    
    public void setChannelAmount(String channelAmount) {
        this.channelAmount = channelAmount;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getManufacturer() {
        return this.manufacturer;
    }
    
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }




}


