package co.edu.usbcali.vas.model;
// Generated Jun 10, 2018 8:14:55 PM by Hibernate Tools 5.1.0.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MailServer generated by hbm2java
 */
public class MailServer  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String name;
     private Integer smtpPort;
     private String smtpHost;
     private String smtpUser;
     private String smtpPass;
     private String smtpSsl;
     private String smtpStarttls;
     private String active;
     private Date createdAt;
     private Date updatedAt;
     private String createdBy;
     private String updatedBy;
     private Set<MailTemplate> mailTemplates = new HashSet<MailTemplate>(0);

    public MailServer() {
    }

	
    public MailServer(Integer id, String code, String name, Integer smtpPort, String smtpHost, Date createdAt, String createdBy) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.smtpPort = smtpPort;
        this.smtpHost = smtpHost;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
    }
    public MailServer(Integer id, String code, String name, Integer smtpPort, String smtpHost, String smtpUser, String smtpPass, String smtpSsl, String smtpStarttls, String active, Date createdAt, Date updatedAt, String createdBy, String updatedBy, Set<MailTemplate> mailTemplates) {
       this.id = id;
       this.code = code;
       this.name = name;
       this.smtpPort = smtpPort;
       this.smtpHost = smtpHost;
       this.smtpUser = smtpUser;
       this.smtpPass = smtpPass;
       this.smtpSsl = smtpSsl;
       this.smtpStarttls = smtpStarttls;
       this.active = active;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.mailTemplates = mailTemplates;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getSmtpPort() {
        return this.smtpPort;
    }
    
    public void setSmtpPort(Integer smtpPort) {
        this.smtpPort = smtpPort;
    }
    public String getSmtpHost() {
        return this.smtpHost;
    }
    
    public void setSmtpHost(String smtpHost) {
        this.smtpHost = smtpHost;
    }
    public String getSmtpUser() {
        return this.smtpUser;
    }
    
    public void setSmtpUser(String smtpUser) {
        this.smtpUser = smtpUser;
    }
    public String getSmtpPass() {
        return this.smtpPass;
    }
    
    public void setSmtpPass(String smtpPass) {
        this.smtpPass = smtpPass;
    }
    public String getSmtpSsl() {
        return this.smtpSsl;
    }
    
    public void setSmtpSsl(String smtpSsl) {
        this.smtpSsl = smtpSsl;
    }
    public String getSmtpStarttls() {
        return this.smtpStarttls;
    }
    
    public void setSmtpStarttls(String smtpStarttls) {
        this.smtpStarttls = smtpStarttls;
    }
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Set<MailTemplate> getMailTemplates() {
        return this.mailTemplates;
    }
    
    public void setMailTemplates(Set<MailTemplate> mailTemplates) {
        this.mailTemplates = mailTemplates;
    }




}


