package co.edu.usbcali.vas.model;
// Generated Jun 10, 2018 8:14:55 PM by Hibernate Tools 5.1.0.Final


import java.util.Date;

/**
 * MailTemplate generated by hbm2java
 */
public class MailTemplate  implements java.io.Serializable {


     private Integer id;
     private MailServer mailServer;
     private String subject;
     private String emailCc;
     private String emailTo;
     private String bodyHtml;
     private String lang;
     private Date createdAt;
     private Date updatedAt;
     private String createdBy;
     private String updatedBy;

    public MailTemplate() {
    }

	
    public MailTemplate(Integer id, Date createdAt, String createdBy) {
        this.id = id;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
    }
    public MailTemplate(Integer id, MailServer mailServer, String subject, String emailCc, String emailTo, String bodyHtml, String lang, Date createdAt, Date updatedAt, String createdBy, String updatedBy) {
       this.id = id;
       this.mailServer = mailServer;
       this.subject = subject;
       this.emailCc = emailCc;
       this.emailTo = emailTo;
       this.bodyHtml = bodyHtml;
       this.lang = lang;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public MailServer getMailServer() {
        return this.mailServer;
    }
    
    public void setMailServer(MailServer mailServer) {
        this.mailServer = mailServer;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getEmailCc() {
        return this.emailCc;
    }
    
    public void setEmailCc(String emailCc) {
        this.emailCc = emailCc;
    }
    public String getEmailTo() {
        return this.emailTo;
    }
    
    public void setEmailTo(String emailTo) {
        this.emailTo = emailTo;
    }
    public String getBodyHtml() {
        return this.bodyHtml;
    }
    
    public void setBodyHtml(String bodyHtml) {
        this.bodyHtml = bodyHtml;
    }
    public String getLang() {
        return this.lang;
    }
    
    public void setLang(String lang) {
        this.lang = lang;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }




}


