package co.edu.usbcali.vas.model;
// Generated Jun 10, 2018 8:14:55 PM by Hibernate Tools 5.1.0.Final


import java.util.Date;

/**
 * MessageBox generated by hbm2java
 */
public class MessageBox  implements java.io.Serializable {


     private Long id;
     private Users users;
     private String subject;
     private String message;
     private String read;
     private String sent;
     private String link;
     private String pictureLink;
     private Date createdAt;
     private Date updatedAt;
     private String createdBy;
     private String updatedBy;

    public MessageBox() {
    }

	
    public MessageBox(Long id, Users users, Date createdAt, String createdBy) {
        this.id = id;
        this.users = users;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
    }
    public MessageBox(Long id, Users users, String subject, String message, String read, String sent, String link, String pictureLink, Date createdAt, Date updatedAt, String createdBy, String updatedBy) {
       this.id = id;
       this.users = users;
       this.subject = subject;
       this.message = message;
       this.read = read;
       this.sent = sent;
       this.link = link;
       this.pictureLink = pictureLink;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public String getRead() {
        return this.read;
    }
    
    public void setRead(String read) {
        this.read = read;
    }
    public String getSent() {
        return this.sent;
    }
    
    public void setSent(String sent) {
        this.sent = sent;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public String getPictureLink() {
        return this.pictureLink;
    }
    
    public void setPictureLink(String pictureLink) {
        this.pictureLink = pictureLink;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }




}


