package co.edu.usbcali.vas.model;
// Generated Jun 10, 2018 8:14:55 PM by Hibernate Tools 5.1.0.Final


import java.util.Date;

/**
 * SystemMonitoringLog generated by hbm2java
 */
public class SystemMonitoringLog  implements java.io.Serializable {


     private Long id;
     private Date actionDate;
     private String actionName;
     private String note;

    public SystemMonitoringLog() {
    }

	
    public SystemMonitoringLog(Long id, Date actionDate, String actionName) {
        this.id = id;
        this.actionDate = actionDate;
        this.actionName = actionName;
    }
    public SystemMonitoringLog(Long id, Date actionDate, String actionName, String note) {
       this.id = id;
       this.actionDate = actionDate;
       this.actionName = actionName;
       this.note = note;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Date getActionDate() {
        return this.actionDate;
    }
    
    public void setActionDate(Date actionDate) {
        this.actionDate = actionDate;
    }
    public String getActionName() {
        return this.actionName;
    }
    
    public void setActionName(String actionName) {
        this.actionName = actionName;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


