package co.edu.usbcali.vas.model;
// Generated Dec 30, 2018 12:40:46 PM by Hibernate Tools 5.1.0.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VideoType generated by hbm2java
 */
public class VideoType  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String description;
     private Date createdAt;
     private Date updatedAt;
     private String createdBy;
     private String updatedBy;
     private Set<Video> videos = new HashSet<Video>(0);

    public VideoType() {
    }

	
    public VideoType(Integer id, String description, Date createdAt, String createdBy) {
        this.id = id;
        this.description = description;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
    }
    public VideoType(Integer id, String code, String description, Date createdAt, Date updatedAt, String createdBy, String updatedBy, Set<Video> videos) {
       this.id = id;
       this.code = code;
       this.description = description;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.videos = videos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Set<Video> getVideos() {
        return this.videos;
    }
    
    public void setVideos(Set<Video> videos) {
        this.videos = videos;
    }




}


